apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: yashraj1999/client
      context: client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yashraj1999/comments
      context: comments
      sync:
        manual:
          - src: '*,js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yashraj1999/event-bus
      context: event-bus
      sync:
        manual:
          - src: '*,js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yashraj1999/moderation
      context: moderation
      sync:
        manual:
          - src: '*,js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yashraj1999/posts
      context: posts
      sync:
        manual:
          - src: '*,js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yashraj1999/query
      context: query
      sync:
        manual:
          - src: '*,js'
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*