apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: yashraj1999/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yashraj1999/client
      context: client
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: yashraj1999/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*